version: "3"
services:
  vpn:
#    image: ghcr.io/bubuntux/nordvpn    # https://github.com/bubuntux/nordvpn
    image: nordvpn #this is self build container of the above to make sure latest nordvpn is installed
    container_name: vpn
    cap_add:
      - NET_ADMIN               # Required
      - NET_RAW                 # Required
    environment:                # Review https://github.com/bubuntux/nordvpn#environment-variables
      - TOKEN=YOUR_OWN_TOKEN_HERE
      - CONNECT=United_States
      - TECHNOLOGY=NordLynx
      - NETWORK=192.168.1.0/24  # So it can be accessed within the local network
    ports:           #espose port here due to network mode
      - 9050:9050
    sysctls:
      - net.ipv6.conf.all.disable_ipv6=1  # Recomended if using ipv4 only

